name: Reuse other workflow

on: [workflow_dispatch]

jobs: 
  dev: 
    uses: './.github/workflows/reusable.yml'
    with: 
      who-to-greet: 'dev'
  qa: 
    uses: './.github/workflows/reusable.yml'
    needs: [dev]
    with: 
      who-to-greet: 'dev'
  qa1: 
    uses: './.github/workflows/reusable.yml'
    needs: [dev]
    with: 
      who-to-greet: 'dev'
  stage: 
    uses: './.github/workflows/reusable.yml'
    needs: [qa, qa1]
    with: 
      who-to-greet: 'dev'
  prod: 
    uses: './.github/workflows/reusable.yml'
    needs: [stage]
    with: 
      who-to-greet: 'dev'
  
 
#   call-workflow: 
#     uses: ./.github/workflows/reusable.yml
#     with: 
#       who-to-greet: '@brox07'

#   use-output:
#     runs-on: ubuntu-latest
#     needs: [call-workflow]
#     steps: 
#       - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
