name: Reusable workflow

on: 
  workflow_call: 
    inputs: 
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: Jim-Bob Billy Thornton
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
        
      - name: Output the current time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
